import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import SearchBar from "@/components/SearchBar";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
      <nav className = 'flex m-2 mx-auto w-7/10'>
        
        <div className="flex p-3">
            <p>Logo</p>
        </div>
        <div className="flex-auto p-1 rounded-full content-center border border-zinc-100 inset-shadow-2xs shadow-2xs hover:shadow-md w-1/100">
          <SearchBar />
        </div>

        <div className="flex-auto">
          <ul className = 'flex justify-end gap-4 content-center'>
          
          <Link href="/"><li className="hover:bg-zinc-200 p-3 rounded-md">Home</li></Link>
          <Link href="/products"><li className="hover:bg-zinc-200 p-3 rounded-md">Popular Products</li></Link>
          <Link href="/"><li className="hover:bg-zinc-200 p-3 rounded-md">Top Price Drops</li></Link>
          <Link href="/"><li className="hover:bg-zinc-200 p-3 rounded-md">Sign up</li></Link>
          <Link href="/"><li className="hover:bg-zinc-200 p-3 rounded-md">Sign in</li></Link>
        </ul></div>
        

      </nav>
      <hr className="border-zinc-300"/>
        {children}
      </body>
    </html>
  );
}
