"""create province_prices table

Revision ID: 801c51ac30c3
Revises: a35124285397
Create Date: 2025-09-19 11:32:27.999875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801c51ac30c3'
down_revision: Union[str, Sequence[str], None] = 'a35124285397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('province_prices',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('retailer', sa.String(), nullable=False),
    sa.Column('province', sa.String(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('regular_price', sa.Float(), nullable=False),
    sa.Column('multi_save_qty', sa.Integer(), nullable=True),
    sa.Column('multi_save_price', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['retailer', 'product_id'], ['products.retailer', 'products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'retailer', 'province')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('province_prices')
    # ### end Alembic commands ###
