"""add price unit column to province price table

Revision ID: 9670fe92aafe
Revises: 98cee3be64f4
Create Date: 2025-09-29 09:11:23.361721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9670fe92aafe'
down_revision: Union[str, Sequence[str], None] = '98cee3be64f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('province_prices', sa.Column('price_unit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('province_prices', 'price_unit')
    # ### end Alembic commands ###
