"""add unit price columns to  province_prices table

Revision ID: 98cee3be64f4
Revises: 801c51ac30c3
Create Date: 2025-09-24 23:10:27.748006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98cee3be64f4'
down_revision: Union[str, Sequence[str], None] = '801c51ac30c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('province_prices', sa.Column('unit_type', sa.String(), nullable=True))
    op.add_column('province_prices', sa.Column('unit_price_kg', sa.String(), nullable=True))
    op.add_column('province_prices', sa.Column('unit_price_lb', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('province_prices', 'unit_price_lb')
    op.drop_column('province_prices', 'unit_price_kg')
    op.drop_column('province_prices', 'unit_type')
    # ### end Alembic commands ###
