"""add_not_null_to_store_columns

Revision ID: 0999233e6d73
Revises: 389135a69ba7
Create Date: 2026-03-23 22:36:00.545022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0999233e6d73'
down_revision: Union[str, Sequence[str], None] = '389135a69ba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'store_province',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stores', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('stores', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stores', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stores', 'store_province',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
