"""drop metro cookies table

Revision ID: 6489f49113e6
Revises: 711dc59717af
Create Date: 2025-10-28 00:09:36.606955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6489f49113e6'
down_revision: Union[str, Sequence[str], None] = '711dc59717af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metro_chain_cookies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metro_chain_cookies',
    sa.Column('store_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('store_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_street', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_province', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_postal', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('jsession_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nsc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('store_id', name=op.f('metro_chain_cookies_pkey'))
    )
    # ### end Alembic commands ###
