"""add_price_unit_and_unit_price_to_price_table

Revision ID: 95b2edeefaf2
Revises: 0999233e6d73
Create Date: 2026-03-26 10:06:18.548684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b2edeefaf2'
down_revision: Union[str, Sequence[str], None] = '0999233e6d73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('price_unit', sa.String(), nullable=True))
    op.add_column('prices', sa.Column('unit_type', sa.String(), nullable=True))
    op.add_column('prices', sa.Column('unit_price_kg', sa.String(), nullable=True))
    op.add_column('prices', sa.Column('unit_price_lb', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prices', 'unit_price_lb')
    op.drop_column('prices', 'unit_price_kg')
    op.drop_column('prices', 'unit_type')
    op.drop_column('prices', 'price_unit')
    # ### end Alembic commands ###
