"""initial migration

Revision ID: a35124285397
Revises: 
Create Date: 2025-09-17 22:54:20.547642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a35124285397'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metro_chain_cookies',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(), nullable=True),
    sa.Column('address_street', sa.String(), nullable=True),
    sa.Column('address_province', sa.String(), nullable=True),
    sa.Column('address_postal', sa.String(), nullable=True),
    sa.Column('jsession_id', sa.String(), nullable=True),
    sa.Column('nsc', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('retailer', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('product_size', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('product_url', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('product_id', 'retailer')
    )
    op.create_table('stores',
    sa.Column('retailer', sa.String(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('store_province', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('retailer', 'store_id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('retailer', sa.String(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('regular_price', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['retailer', 'product_id'], ['products.retailer', 'products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retailer', 'store_id'], ['stores.retailer', 'stores.store_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prices',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('retailer', sa.String(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('regular_price', sa.Float(), nullable=False),
    sa.Column('multi_save_qty', sa.Integer(), nullable=True),
    sa.Column('multi_save_price', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['retailer', 'product_id'], ['products.retailer', 'products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retailer', 'store_id'], ['stores.retailer', 'stores.store_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'retailer', 'store_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_tokens')
    op.drop_table('prices')
    op.drop_table('price_history')
    op.drop_table('oauth_accounts')
    op.drop_table('users')
    op.drop_table('stores')
    op.drop_table('products')
    op.drop_table('metro_chain_cookies')
    # ### end Alembic commands ###
