export const CATEGORIES = [
  "Baking and Spices",
  "Baking Ingredients & Supplies",
  "Bakery Snacks & Treats",
  "Bottled Water",
  "Bread & Bakery Products",
  "Butter & Margarine",
  "Cereal & Breakfast",
  "Chicken & Turkey",
  "Chips",
  "Condiments & Sauces",
  "Condiments, Sauces and Oils",
  "Cookies, Muffins & Desserts",
  "Cooking Oils",
  "Crackers",
  "Crackers & Cookies",
  "Cream & Creamers",
  "Dairy",
  "Dried Beans, Vegetables & Grains",
  "Dried Fruits & Nuts",
  "Drink Mixes",
  "Egg & Egg Substitutes",
  "Energy Drinks",
  "English Muffins & Crumpets",
  "Fresh Beef",
  "Fresh Fruits",
  "Fresh Pâté, Olives & Antipasti",
  "Fresh Salads, Dressings & Toppings",
  "Fresh Sausages",
  "Fresh Vegetables",
  "Frozen",
  "Frozen Breakfast",
  "Frozen Fruit & Vegetables",
  "Frozen Meat, Seafood & Alternatives",
  "Frozen Vegetables",
  "Fruits & Vegetables",
  "Garlic & Cheese Breads",
  "Indian & South Asian Food",
  "Lactose Free",
  "Latin American Foods",
  "Lunch Bags & Coolers",
  "Maple Syrup & Table Syrup",
  "Meals, Entrees & Sides",
  "Meat & Poultry",
  "Meatless Alternatives",
  "Mexican & Latin American Food",
  "Milk & Cream",
  "Muffins",
  "Nuts, Dried Fruit & Trail Mixes",
  "Packaged Salad & Dressing",
  "Pasta & Pasta Sauce",
  "Pasta and Side Dishes",
  "Pork & Ham",
  "Sauces & Gravy",
  "Sliced Bread",
  "Snacks",
  "Snacks, Chips & Candy",
  "Soups, Stews & Chilis",
  "Sour Cream & Dips",
  "Spices & Seasonings",
  "Tea",
  "Thai & Southeast Asian Food",
  "Vinegar",
  "Wraps, Flatbread & Pizza Crust",
];

export const RETAILERS = [
  "Walmart",
  "Loblaws",
  "No Frills",
  "Zehrs",
  "Independent",
  "Valu-Mart",
  "Real Canadian Superstore",
  "Real Atlantic Superstore",
];